// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuSbWYS9zVECru2lv1ztJHrMEMtutJhX4',
    appId: '1:56467441228:web:766dd88cefac4d874bd6e9',
    messagingSenderId: '56467441228',
    projectId: 'moniman-63c48',
    authDomain: 'moniman-63c48.firebaseapp.com',
    storageBucket: 'moniman-63c48.appspot.com',
    measurementId: 'G-RTS27GS9J4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNq0-u-4yw42w_ztPEBO2k_QNwHF-F5Jg',
    appId: '1:56467441228:android:7ce215e74ef85ec44bd6e9',
    messagingSenderId: '56467441228',
    projectId: 'moniman-63c48',
    storageBucket: 'moniman-63c48.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoAg7nWCBIXjWYBgRTR0j8GMXTOimUYyM',
    appId: '1:56467441228:ios:85f6477c3e80111f4bd6e9',
    messagingSenderId: '56467441228',
    projectId: 'moniman-63c48',
    storageBucket: 'moniman-63c48.appspot.com',
    iosClientId: '56467441228-dam32sm65aqm2d0l925oo4qft4orqo1i.apps.googleusercontent.com',
    iosBundleId: 'app.moniman.pay',
  );

}